"""Constants and endpoint catalog for the MOCO CLI."""

from __future__ import annotations

from typing import Final

API_KEY_ENV_VAR: Final = "MOCO_API_KEY"
DOMAIN_ENV_VAR: Final = "MOCO_DOMAIN"
BASE_URL_ENV_VAR: Final = "MOCO_BASE_URL"
IMPERSONATE_USER_ID_ENV_VAR: Final = "MOCO_IMPERSONATE_USER_ID"
API_BASE_URL_TEMPLATE: Final = "https://{domain}.mocoapp.com/api/v1"
DOCS_REPO_URL: Final = "https://github.com/everii-group/mocoapp-api-docs"
DOCS_SNAPSHOT_DATE: Final = "2026-02-18"
DEFAULT_TIMEOUT_SECONDS: Final = 30
VALID_HTTP_METHODS: Final[tuple[str, ...]] = ("GET", "POST", "PUT", "PATCH", "DELETE")

# Tuple item format: (method, path, section, source_file, source_line)
RAW_ENDPOINTS: Final[tuple[tuple[str, str, str, str, int], ...]] = (
    ("GET", "/account/catalog_services", "Catalog Services", "account/catalog_services.md", 85),
    ("GET", "/account/catalog_services/{id}", "Catalog Services", "account/catalog_services.md", 101),
    ("POST", "/account/catalog_services", "Catalog Services", "account/catalog_services.md", 113),
    ("PUT", "/account/catalog_services/{id}", "Catalog Services", "account/catalog_services.md", 142),
    ("DELETE", "/account/catalog_services/{id}", "Catalog Services", "account/catalog_services.md", 158),
    ("GET", "/account/catalog_services/{service_id}/items/{id}", "Catalog Services", "account/catalog_services.md", 168),
    ("POST", "/account/catalog_services/{service_id}/items", "Catalog Services", "account/catalog_services.md", 178),
    ("PUT", "/account/catalog_services/{service_id}/items/{id}", "Catalog Services", "account/catalog_services.md", 197),
    ("DELETE", "/account/catalog_services/{service_id}/items/{id}", "Catalog Services", "account/catalog_services.md", 216),
    ("GET", "/account/custom_properties", "Custom Properties", "account/custom_properties.md", 42),
    ("GET", "/account/custom_properties/{id}", "Custom Properties", "account/custom_properties.md", 59),
    ("POST", "/account/custom_properties", "Custom Properties", "account/custom_properties.md", 71),
    ("PATCH", "/account/custom_properties/{id}", "Custom Properties", "account/custom_properties.md", 101),
    ("DELETE", "/account/custom_properties/{id}", "Custom Properties", "account/custom_properties.md", 119),
    ("GET", "/account/expense_templates", "Expense Templates", "account/expense_templates.md", 46),
    ("GET", "/account/expense_templates/{id}", "Expense Templates", "account/expense_templates.md", 62),
    ("POST", "/account/expense_templates", "Expense Templates", "account/expense_templates.md", 74),
    ("PUT", "/account/expense_templates/{id}", "Expense Templates", "account/expense_templates.md", 93),
    ("DELETE", "/account/expense_templates/{id}", "Expense Templates", "account/expense_templates.md", 107),
    ("GET", "/account/fixed_costs", "Fixed Costs", "account/fixed_costs.md", 46),
    ("GET", "/account/hourly_rates", "Hourly Rates", "account/hourly_rates.md", 15),
    ("GET", "/account/internal_hourly_rates", "Internal Hourly Rates", "account/internal_hourly_rates.md", 15),
    ("PATCH", "/account/internal_hourly_rates", "Internal Hourly Rates", "account/internal_hourly_rates.md", 66),
    ("GET", "/account/task_templates", "Task Templates", "account/task_templates.md", 45),
    ("GET", "/account/task_templates/{id}", "Task Templates", "account/task_templates.md", 61),
    ("POST", "/account/task_templates", "Task Templates", "account/task_templates.md", 73),
    ("PUT", "/account/task_templates/{id}", "Task Templates", "account/task_templates.md", 93),
    ("DELETE", "/account/task_templates/{id}", "Task Templates", "account/task_templates.md", 107),
    ("GET", "/activities", "Activities", "activities.md", 68),
    ("GET", "/activities/{id}", "Activities", "activities.md", 93),
    ("POST", "/activities", "Activities", "activities.md", 103),
    ("POST", "/activities/bulk", "Activities", "activities.md", 136),
    ("PUT", "/activities/{id}", "Activities", "activities.md", 165),
    ("PATCH", "/activities/{id}/start_timer", "Activities", "activities.md", 181),
    ("PATCH", "/activities/{id}/stop_timer", "Activities", "activities.md", 195),
    ("DELETE", "/activities/{id}", "Activities", "activities.md", 206),
    ("POST", "/activities/disregard", "Activities", "activities.md", 219),
    ("GET", "/comments", "Comments", "comments.md", 38),
    ("GET", "/comments/{id}", "Comments", "comments.md", 58),
    ("POST", "/comments", "Comments", "comments.md", 70),
    ("POST", "/comments/bulk", "Comments", "comments.md", 95),
    ("PUT", "/comments/{id}", "Comments", "comments.md", 117),
    ("DELETE", "/comments/{id}", "Comments", "comments.md", 133),
    ("GET", "/companies", "Companies", "companies.md", 92),
    ("GET", "/companies/{id}", "Companies", "companies.md", 116),
    ("POST", "/companies", "Companies", "companies.md", 128),
    ("PUT", "/companies/{id}", "Companies", "companies.md", 180),
    ("DELETE", "/companies/{id}", "Companies", "companies.md", 196),
    ("PUT", "/companies/{id}/archive", "Companies", "companies.md", 204),
    ("PUT", "/companies/{id}/unarchive", "Companies", "companies.md", 215),
    ("GET", "/contacts/people", "Contacts", "contacts.md", 49),
    ("GET", "/contacts/people/{id}", "Contacts", "contacts.md", 68),
    ("POST", "/contacts/people", "Contacts", "contacts.md", 80),
    ("PUT", "/contacts/people/{id}", "Contacts", "contacts.md", 116),
    ("DELETE", "/contacts/people/{id}", "Contacts", "contacts.md", 132),
    ("GET", "/deal_categories", "Deal Categories", "deal_categories.md", 28),
    ("GET", "/deal_categories/{id}", "Deal Categories", "deal_categories.md", 44),
    ("POST", "/deal_categories", "Deal Categories", "deal_categories.md", 56),
    ("PUT", "/deal_categories/{id}", "Deal Categories", "deal_categories.md", 76),
    ("DELETE", "/deal_categories/{id}", "Deal Categories", "deal_categories.md", 92),
    ("GET", "/deals", "Deals / Leads", "deals.md", 67),
    ("GET", "/deals/{id}", "Deals / Leads", "deals.md", 87),
    ("POST", "/deals", "Deals / Leads", "deals.md", 99),
    ("PUT", "/deals/{id}", "Deals / Leads", "deals.md", 135),
    ("DELETE", "/deals/{id}", "Deals / Leads", "deals.md", 151),
    ("GET", "/users/employments", "User Employments", "employments.md", 40),
    ("POST", "/users/employments", "User Employments", "employments.md", 58),
    ("GET", "/users/employments/{id}", "User Employments", "employments.md", 85),
    ("PUT", "/users/employments/{id}", "User Employments", "employments.md", 95),
    ("DELETE", "/users/employments/{id}", "User Employments", "employments.md", 114),
    ("GET", "/users/holidays", "User Holidays", "holidays.md", 45),
    ("GET", "/users/holidays/{id}", "User Holidays", "holidays.md", 63),
    ("POST", "/users/holidays", "User Holidays", "holidays.md", 73),
    ("PUT", "/users/holidays/{id}", "User Holidays", "holidays.md", 98),
    ("DELETE", "/users/holidays/{id}", "User Holidays", "holidays.md", 114),
    ("GET", "/invoices/bookkeeping_exports", "Invoice Bookkeeping Exports", "invoice_bookkeeping_exports.md", 71),
    ("GET", "/invoices/bookkeeping_exports/{id}", "Invoice Bookkeeping Exports", "invoice_bookkeeping_exports.md", 81),
    ("POST", "/invoices/bookkeeping_exports", "Invoice Bookkeeping Exports", "invoice_bookkeeping_exports.md", 91),
    ("GET", "/invoices/payments", "Invoice Payments", "invoice_payments.md", 36),
    ("GET", "/invoices/payments/{id}", "Invoice Payments", "invoice_payments.md", 53),
    ("POST", "/invoices/payments", "Invoice Payments", "invoice_payments.md", 63),
    ("POST", "/invoices/payments/bulk", "Invoice Payments", "invoice_payments.md", 89),
    ("DELETE", "/invoices/payments/{id}", "Invoice Payments", "invoice_payments.md", 139),
    ("GET", "/invoice_reminders", "Invoice Reminders", "invoice_reminders.md", 40),
    ("GET", "/invoice_reminders/{id}", "Invoice Reminders", "invoice_reminders.md", 57),
    ("POST", "/invoice_reminders", "Invoice Reminders", "invoice_reminders.md", 67),
    ("DELETE", "/invoice_reminders/{id}", "Invoice Reminders", "invoice_reminders.md", 96),
    ("POST", "/invoice_reminders/{id}/send_email", "Invoice Reminders", "invoice_reminders.md", 106),
    ("GET", "/invoices", "Invoices", "invoices.md", 240),
    ("GET", "/invoices/locked", "Invoices", "invoices.md", 270),
    ("GET", "/invoices/{id}", "Invoices", "invoices.md", 289),
    ("GET", "/invoices/{id}.pdf", "Invoices", "invoices.md", 301),
    ("GET", "/invoices/{id}/timesheet", "Invoices", "invoices.md", 318),
    ("GET", "/invoices/{id}/timesheet.pdf", "Invoices", "invoices.md", 370),
    ("GET", "/invoices/{id}/expenses", "Invoices", "invoices.md", 386),
    ("PUT", "/invoices/{id}/update_status", "Invoices", "invoices.md", 439),
    ("POST", "/invoices", "Invoices", "invoices.md", 458),
    ("POST", "/invoices/{id}/send_email", "Invoices", "invoices.md", 587),
    ("DELETE", "/invoices/{id}", "Invoices", "invoices.md", 614),
    ("GET", "/invoices/{id}/attachments", "Invoices", "invoices.md", 632),
    ("POST", "/invoices/{invoice_id}/attachments", "Invoices", "invoices.md", 644),
    ("DELETE", "/invoices/{invoice_id}/attachments/{id}", "Invoices", "invoices.md", 663),
    ("GET", "/offers/{id}/customer_approval", "Offer Customer Approval", "offer_customer_approval.md", 31),
    ("POST", "/offers/{id}/customer_approval/activate", "Offer Customer Approval", "offer_customer_approval.md", 44),
    ("POST", "/offers/{id}/customer_approval/deactivate", "Offer Customer Approval", "offer_customer_approval.md", 56),
    ("GET", "/offers", "Offers", "offers.md", 192),
    ("GET", "/offers/{id}", "Offers", "offers.md", 223),
    ("GET", "/offers/{id}.pdf", "Offers", "offers.md", 235),
    ("POST", "/offers", "Offers", "offers.md", 251),
    ("PUT", "/offers/{id}/assign", "Offers", "offers.md", 330),
    ("PUT", "/offers/{id}/update_status", "Offers", "offers.md", 349),
    ("POST", "/offers/{id}/send_email", "Offers", "offers.md", 365),
    ("GET", "/offers/{id}/attachments", "Offers", "offers.md", 391),
    ("POST", "/offers/{id}/attachments", "Offers", "offers.md", 403),
    ("DELETE", "/offers/{offer_id}/attachments/{id}", "Offers", "offers.md", 422),
    ("GET", "/planning_entries", "Planning Entries", "planning_entries.md", 66),
    ("GET", "/planning_entries/{id}", "Planning Entries", "planning_entries.md", 86),
    ("POST", "/planning_entries", "Planning Entries", "planning_entries.md", 96),
    ("PUT", "/planning_entries/{id}", "Planning Entries", "planning_entries.md", 129),
    ("DELETE", "/planning_entries/{id}", "Planning Entries", "planning_entries.md", 145),
    ("GET", "/users/presences", "User Presences", "presences.md", 37),
    ("GET", "/users/presences/{id}", "User Presences", "presences.md", 56),
    ("POST", "/users/presences", "User Presences", "presences.md", 66),
    ("POST", "/users/presences/touch", "User Presences", "presences.md", 91),
    ("PUT", "/users/presences/{id}", "User Presences", "presences.md", 127),
    ("DELETE", "/users/presences/{id}", "User Presences", "presences.md", 143),
    ("GET", "/profile", "Profile", "profile.md", 13),
    ("GET", "/projects/{id}/contracts", "Project Contracts", "project_contracts.md", 33),
    ("GET", "/projects/{id}/contracts/{id}", "Project Contracts", "project_contracts.md", 45),
    ("POST", "/projects/{id}/contracts", "Project Contracts", "project_contracts.md", 55),
    ("PUT", "/projects/{id}/contracts/{id}", "Project Contracts", "project_contracts.md", 78),
    ("DELETE", "/projects/{id}/contracts/{id}", "Project Contracts", "project_contracts.md", 94),
    ("GET", "/projects/{id}/expenses", "Project Expenses", "project_expenses.md", 88),
    ("GET", "/projects/{id}/expenses/{id}", "Project Expenses", "project_expenses.md", 108),
    ("POST", "/projects/{id}/expenses", "Project Expenses", "project_expenses.md", 118),
    ("POST", "/projects/{id}/expenses/bulk", "Project Expenses", "project_expenses.md", 160),
    ("PUT", "/projects/{id}/expenses/{id}", "Project Expenses", "project_expenses.md", 209),
    ("DELETE", "/projects/{id}/expenses/{id}", "Project Expenses", "project_expenses.md", 225),
    ("POST", "/projects/{id}/expenses/disregard", "Project Expenses", "project_expenses.md", 237),
    ("GET", "/projects/expenses", "Project Expenses", "project_expenses.md", 257),
    ("GET", "/projects/groups", "Project Group", "project_groups.md", 57),
    ("GET", "/projects/groups/{id}", "Project Group", "project_groups.md", 75),
    ("GET", "/projects/payment_schedules", "Project Payment Schedules", "project_payment_schedules.md", 37),
    ("GET", "/projects/{project_id}/payment_schedules", "Project Payment Schedules", "project_payment_schedules.md", 56),
    ("GET", "/projects/{project_id}/payment_schedules/{id}", "Project Payment Schedules", "project_payment_schedules.md", 72),
    ("POST", "/projects/{project_id}/payment_schedules", "Project Payment Schedules", "project_payment_schedules.md", 82),
    ("PUT", "/projects/{project_id}/payment_schedules/{id}", "Project Payment Schedules", "project_payment_schedules.md", 105),
    ("DELETE", "/projects/{project_id}/payment_schedules/{id}", "Project Payment Schedules", "project_payment_schedules.md", 125),
    ("GET", "/recurring_expenses", "Project Recurring Expenses", "project_recurring_expenses.md", 58),
    ("GET", "/projects/{id}/recurring_expenses", "Project Recurring Expenses", "project_recurring_expenses.md", 74),
    ("GET", "/projects/{id}/recurring_expenses/{id}", "Project Recurring Expenses", "project_recurring_expenses.md", 84),
    ("POST", "/projects/{id}/recurring_expenses", "Project Recurring Expenses", "project_recurring_expenses.md", 94),
    ("PUT", "/projects/{id}/recurring_expenses/{id}", "Project Recurring Expenses", "project_recurring_expenses.md", 131),
    ("POST", "/projects/{id}/recurring_expenses/{id}/recur", "Project Recurring Expenses", "project_recurring_expenses.md", 146),
    ("DELETE", "/projects/{id}/recurring_expenses/{id}", "Project Recurring Expenses", "project_recurring_expenses.md", 160),
    ("GET", "/projects/{id}/tasks", "Project Tasks", "project_tasks.md", 36),
    ("GET", "/projects/{id}/tasks/{id}", "Project Tasks", "project_tasks.md", 48),
    ("POST", "/projects/{id}/tasks", "Project Tasks", "project_tasks.md", 58),
    ("PUT", "/projects/{id}/tasks/{id}", "Project Tasks", "project_tasks.md", 83),
    ("DELETE", "/projects/{id}/tasks/{id}", "Project Tasks", "project_tasks.md", 100),
    ("DELETE", "/projects/{id}/tasks/destroy_all", "Project Tasks", "project_tasks.md", 111),
    ("GET", "/projects", "Projects", "projects.md", 137),
    ("GET", "/projects/assigned", "Projects", "projects.md", 166),
    ("GET", "/projects/{id}", "Projects", "projects.md", 210),
    ("POST", "/projects", "Projects", "projects.md", 222),
    ("PUT", "/projects/{id}", "Projects", "projects.md", 278),
    ("DELETE", "/projects/{id}", "Projects", "projects.md", 294),
    ("PUT", "/projects/{id}/archive", "Projects", "projects.md", 305),
    ("PUT", "/projects/{id}/unarchive", "Projects", "projects.md", 316),
    ("GET", "/projects/{id}/report", "Projects", "projects.md", 327),
    ("PUT", "/projects/{id}/share", "Projects", "projects.md", 377),
    ("PUT", "/projects/{id}/disable_share", "Projects", "projects.md", 398),
    ("PUT", "/projects/{id}/assign_project_group", "Projects", "projects.md", 419),
    ("PUT", "/projects/{id}/unassign_project_group", "Projects", "projects.md", 433),
    ("GET", "/purchases/bookkeeping_exports", "Purchase Bookkeeping Exports", "purchase_bookkeeping_exports.md", 71),
    ("GET", "/purchases/bookkeeping_exports/{id}", "Purchase Bookkeeping Exports", "purchase_bookkeeping_exports.md", 81),
    ("POST", "/purchases/bookkeeping_exports", "Purchase Bookkeeping Exports", "purchase_bookkeeping_exports.md", 91),
    ("GET", "/purchases/budgets", "Purchase Budgets", "purchase_budgets.md", 31),
    ("GET", "/purchases/categories", "Purchase Categories", "purchase_categories.md", 29),
    ("GET", "/purchases/categories/{id}", "Purchase Categories", "purchase_categories.md", 45),
    ("GET", "/purchases/drafts", "Purchase Drafts", "purchase_drafts.md", 35),
    ("GET", "/purchases/drafts/{id}", "Purchase Drafts", "purchase_drafts.md", 51),
    ("GET", "/purchases/drafts/{id}.pdf", "Purchase Drafts", "purchase_drafts.md", 63),
    ("DELETE", "/purchases/drafts/{id}", "Purchase Drafts", "purchase_drafts.md", 75),
    ("GET", "/purchases/payments", "Purchase Payments", "purchase_payments.md", 33),
    ("GET", "/purchases/payments/{id}", "Purchase Payments", "purchase_payments.md", 50),
    ("POST", "/purchases/payments", "Purchase Payments", "purchase_payments.md", 60),
    ("POST", "/purchases/payments/bulk", "Purchase Payments", "purchase_payments.md", 83),
    ("DELETE", "/purchases/payments/{id}", "Purchase Payments", "purchase_payments.md", 126),
    ("GET", "/purchases", "Purchases", "purchases.md", 107),
    ("GET", "/purchases/{id}", "Purchases", "purchases.md", 134),
    ("POST", "/purchases", "Purchases", "purchases.md", 146),
    ("PUT", "/purchases/{id}", "Purchases", "purchases.md", 206),
    ("POST", "/purchases/{id}/assign_to_project", "Purchases", "purchases.md", 225),
    ("PATCH", "/purchases/{id}/update_status", "Purchases", "purchases.md", 260),
    ("PATCH", "/purchases/{id}/store_document", "Purchases", "purchases.md", 277),
    ("DELETE", "/purchases/{id}", "Purchases", "purchases.md", 291),
    ("GET", "/receipts", "Receipts", "receipts.md", 67),
    ("GET", "/receipts/{id}", "Receipts", "receipts.md", 90),
    ("POST", "/receipts", "Receipts", "receipts.md", 102),
    ("PATCH", "/receipts/{id}", "Receipts", "receipts.md", 146),
    ("DELETE", "/receipts/{id}", "Receipts", "receipts.md", 178),
    ("GET", "/report/absences", "Reports", "reports.md", 13),
    ("GET", "/report/cashflow", "Reports", "reports.md", 46),
    ("GET", "/report/finance", "Reports", "reports.md", 88),
    ("GET", "/report/planned_vs_tracked", "Reports", "reports.md", 130),
    ("GET", "/report/utilization", "Reports", "reports.md", 180),
    ("GET", "/schedules", "Schedules", "schedules.md", 48),
    ("GET", "/schedules/{id}", "Schedules", "schedules.md", 69),
    ("POST", "/schedules", "Schedules", "schedules.md", 79),
    ("PUT", "/schedules/{id}", "Schedules", "schedules.md", 107),
    ("DELETE", "/schedules/{id}", "Schedules", "schedules.md", 123),
    ("GET", "/taggings", "Taggings (tag associations)", "tags/taggings.md", 22),
    ("PATCH", "/taggings", "Taggings (tag associations)", "tags/taggings.md", 37),
    ("PUT", "/taggings", "Taggings (tag associations)", "tags/taggings.md", 57),
    ("DELETE", "/taggings", "Taggings (tag associations)", "tags/taggings.md", 79),
    ("GET", "/tags", "Tags", "tags/tags.md", 26),
    ("GET", "/tags/{id}", "Tags", "tags/tags.md", 42),
    ("POST", "/tags", "Tags", "tags/tags.md", 52),
    ("PUT", "/tags/{id}", "Tags", "tags/tags.md", 76),
    ("DELETE", "/tags/{id}", "Tags", "tags/tags.md", 92),
    ("GET", "/units", "Units / Teams", "units.md", 42),
    ("GET", "/units/{id}", "Units / Teams", "units.md", 58),
    ("POST", "/units", "Units / Teams", "units.md", 68),
    ("PUT", "/units/{id}", "Units / Teams", "units.md", 85),
    ("DELETE", "/users/{id}", "Units / Teams", "units.md", 101),
    ("GET", "/users/roles", "User permission roles", "user_roles.md", 43),
    ("GET", "/users", "Users", "users.md", 50),
    ("GET", "/users/{id}", "Users", "users.md", 68),
    ("POST", "/users", "Users", "users.md", 80),
    ("PUT", "/users/{id}", "Users", "users.md", 123),
    ("DELETE", "/users/{id}", "Users", "users.md", 140),
    ("GET", "/users/{id}/performance_report", "Users", "users.md", 151),
    ("GET", "/vat_code_sales", "VAT Codes", "vat_codes.md", 45),
    ("GET", "/vat_code_purchases", "VAT Codes", "vat_codes.md", 64),
    ("GET", "/vat_code_sales/{id}", "VAT Codes", "vat_codes.md", 83),
    ("GET", "/vat_code_purchases/{id}", "VAT Codes", "vat_codes.md", 95),
    ("GET", "/account/web_hooks", "Web Hooks", "web_hooks.md", 26),
    ("GET", "/account/web_hooks/{id}", "Web Hooks", "web_hooks.md", 42),
    ("POST", "/account/web_hooks", "Web Hooks", "web_hooks.md", 54),
    ("PUT", "/account/web_hooks/{id}", "Web Hooks", "web_hooks.md", 76),
    ("PUT", "/account/web_hooks/{id}/disable", "Web Hooks", "web_hooks.md", 92),
    ("PUT", "/account/web_hooks/{id}/enable", "Web Hooks", "web_hooks.md", 102),
    ("DELETE", "/account/web_hooks/{id}", "Web Hooks", "web_hooks.md", 112),
    ("GET", "/users/work_time_adjustments", "User Work Time Adjustments", "work_time_adjustments.md", 42),
    ("GET", "/users/work_time_adjustments/{id}", "User Work Time Adjustments", "work_time_adjustments.md", 61),
    ("POST", "/users/work_time_adjustments", "User Work Time Adjustments", "work_time_adjustments.md", 71),
    ("PUT", "/users/work_time_adjustments/{id}", "User Work Time Adjustments", "work_time_adjustments.md", 95),
    ("DELETE", "/users/work_time_adjustments/{id}", "User Work Time Adjustments", "work_time_adjustments.md", 109),
)

ENDPOINT_COUNT: Final = len(RAW_ENDPOINTS)
